In [1]:
import pandas as pd

In [2]:
data = {
    "Driver": ["Hamilton", "Verstappen", "Leclerc", "Norris"],
    "Team": ["Mercedes", "Red Bull", "Ferrari", "McLaren"],
    "Wins": [105, 65, 8, 5]
}

df = pd.DataFrame(data)

df

       Driver      Team  Wins
0    Hamilton  Mercedes   105
1  Verstappen  Red Bull    65
2     Leclerc   Ferrari     8
3      Norris   McLaren     5

In [3]:
df["Driver"]

0      Hamilton
1    Verstappen
2       Leclerc
3        Norris
Name: Driver, dtype: object

In [4]:
df["Wins"]

0    105
1     65
2      8
3      5
Name: Wins, dtype: int64

In [5]:
df["Wins"].mean()

np.float64(45.75)

In [6]:
df["Wins"].max()

105

In [7]:
df["Wins"].min()

5

In [8]:
df[df["Wins"] > 10]

       Driver      Team  Wins
0    Hamilton  Mercedes   105
1  Verstappen  Red Bull    65